### ISSUE TITLE
Tests for ns macro with require

### ISSUE THREAD

**Issue by tomasz-biernacki** [ScalaConsultants/replumb#101]
Add tests for `ns` macro for `include-macros` and `refer-macros` like [here](https://github.com/clojure/clojurescript/wiki/Differences-from-Clojure#namespaces).

Eg.
```
(ns testme.core
  (:require [foo.core :as foo :refer [foo-fn] :include-macros true]
            [woz.core :as woz :refer [woz-fn] :refer-macros [apple jax]]))
```

**Comment by arichiardi** [comment]
So this one is not part of #97 right?

**Comment by tomasz-biernacki** [comment]
No, this will be a separate branch. One for `require-macros`, one for `require` and one for the `cljc` file. It's better to separate them.

**Comment by arichiardi** [comment]
:+1:
