### ISSUE TITLE
allow module "preloading"

### ISSUE THREAD

**Issue by jaredly** [ScalaConsultants/replumb#130]
I'd like to be able to "preload" modules into the repl runtime, w/o going through the whole "eval & xhr load everything" process. 

I can cheat a bit and do `(swap! cljs.js/*loaded* conj 'clojure.string)` and then `(require 'clojure.string)` will bypass file loading, but I don't get `apropos` support ;( b/c replumb (or the compiler state) doesn't know about the clojure.string interns...

**Comment by arichiardi** [comment]
Hello @jaredly! Can you expand a bit your use case? Do you want to avoid loading the file?

Apropos cannot work if the file is not loaded and this is expected.

You could plug a custom load-fn that does nothing (returns an empty string, see the top of replumb.load)...if I understood right..

Pre loading is in the queue, but it will require the namespace...

**Comment by jaredly** [comment]
If I do a custom load-fn that does nothing, then apropos still doesn't work -- although I'm less concerned about that (I can get that w/ namespace enumeration) -- I'm wondering if there's a way to get the docstrings of functions after the fact -- w/o re-compiling the namespaces

**Comment by arichiardi** [comment]
If by recompiling you mean analyzing, I don't think so, but I have to say that I have never investigated where the docstring is stored in the AST.
Given that it is metadata, probably in the `:meta` key but I don't think anywhere else than the AST. Thusly you need to pass your namespace to analyzer by requiring it.
Again, these are conjectures without having double checked...

**Comment by arichiardi** [comment]
I think for pre-loading docstring you need a custom solution, btw if you have it I am curious to see it, I am closing ok?

**Comment by jaredly** [comment]
+1 sounds good. yeah for the short term I am just parsing the relevant cljs file ahead of time and side-loading in the docs
