### ISSUE TITLE
`ns` form handled incorrectly

### ISSUE THREAD

**Issue by jaredly** [ScalaConsultants/replumb#131]
if I eval
```
(ns one.thing)
(defn awesome [] 10)
```
then `awesome` is defined in the namespace `cljs.user`, but the working namespace changes to `one.thing`.
See repl session:
![image](https://cloud.githubusercontent.com/assets/112170/12424466/8fd43092-be8d-11e5-82b2-91c3cd5152d6.png)

**Comment by arichiardi** [comment]
You mean two forms in a single `read-eval-call`? That's never been taken into consideration I guess...and it might have some problem yes.

**Comment by jaredly** [comment]
yup. `cljs.js/eval-string` handles multiple forms just fine, so I'm not sure where the breakdown would be

**Comment by jaredly** [comment]
oh looks like it was my fault. I was wrapping everything in a `(do )` (to try and work around that other weird bug...)
so
```
(ns one.thing)
(defn awesome [] 10)
```
works if I don't wrap everything in a `do` block...
but then
```
(ns one.thing)
(defn a 10)
(defn b 20)
```
breaks b/c it tries to eval `((defn a 10) (defn b 20))` (calling the result of the first defn w/ the second defn)...
and now
```
(ns one.thing)
(do
  (defn a 10)
  (defn b 20))
```
works, but now I need a way to transform the first thing into the second...

**Comment by jaredly** [comment]
ahhhhh so the issue is the eval-str option `:context`. If `:context` is `:expr` then it does the weird "multiple forms get coerced into a function call unless it's an ns macro :P". If `:context` is `:statement` then it handles multiple things fine, but it doesn't return the last value...
I wish there was a hybrid mode that handled multiple forms, and returned the value of the last form :// (this is how javascript's `eval` works....) so maybe it's just a bug that `:expr` does weird things w/ multiple forms.

**Comment by arichiardi** [comment]
Yes that is it, I can expose that option in case you need it, but I don't think it would solve your problem.
If JS eval works like that, a super hack can be to js `eval` two `read-eval-call`...but I am not a JS expert.

**Comment by jaredly** [comment]
yeah it would be helpful to expose the `:context` vbl -- I can work around the lack of return value. right now I'm rolling my own `cljs/eval-str` in the case of multiple forms, just so I can change the `:context` arg

**Comment by arichiardi** [comment]
Will do, which one is priority for you? We are looking at three issues and it is better to focus on the blocking one. This one I guess?

**Comment by arichiardi** [comment]
Thank for investigating BTW, I would like to create a PROJECTS.MD file where we can add your REPL as well as other replumb projects

**Comment by jaredly** [comment]
nope, this isn't blocking b/c I just made my own :D so you can do whatever.

**Comment by arichiardi** [comment]
:+1:

**Comment by jaredly** [comment]
closing in favor of #129
