### ISSUE TITLE
Dirty git repo after testing (deleted cache files)

### ISSUE THREAD

**Issue by arichiardi** [ScalaConsultants/replumb#137]
After running `lein test-node*` or similar, the `git status` command complains:

```
deleted:    dev-resources/private/test/cache/clojure_SLASH_set.cache.json
deleted:    dev-resources/private/test/cache/clojure_SLASH_set.js
```

@tomasz-biernacki can you have a look if you can?

**Comment by tomasz-biernacki** [comment]
Yes, probably is because of tests, in which I'm testing the presence of cache files.
