### ISSUE TITLE
Source support

### ISSUE THREAD

**Issue by arichiardi** [ScalaConsultants/replumb#17]
There is no support for `source` at the moment.

See https://github.com/mfikes/planck/blob/master/planck-cljs/src/planck/repl.cljs#L572 for inspiration.

This can now be easily added thanks to `read-file-fn` and co.

**Comment by tomasz-biernacki** [comment]
@mfikes hi Mike, I'm trying to replicate the `source` functionality in replumb and I saw that you have something similar in planck. I saw your code and I have one question regarding [this if branch](https://github.com/mfikes/planck/blob/577402f02947e3220ae8c10318c86aa0b773241a/planck-cljs/src/planck/repl.cljs#L576): could you give me an example in which you enter that branch? 
From my experiments `(source +)` `map` and `clojure.set/union` seem to fall into the [else branch](https://github.com/mfikes/planck/blob/577402f02947e3220ae8c10318c86aa0b773241a/planck-cljs/src/planck/repl.cljs#L583)

**Comment by mfikes** [comment]
@tomasz-biernacki When you load a namespace using `cljs.js/*load-fn*`, its API doesn't allow client code to indicate anything that could be placed in `:file` in the AST. So you end up with `nil`. But, the `:file` inside the `:meta` key in the AST ends up having the namespace symbol. So, I hacked Planck to then re-attempt to find the file which may have been the source of the namespace.

While the goals of Planck have been to flesh out the features visible to the end-user without worrying _too_ much about the underlying hacks that may be involved to achieve them, Replumb may have slightly different goals (features + clean code), and in that case it might make sense to see if it is feasible to revise the `cljs.js/*load-fn*` API allowing it to optionally include a `:file` in the returned map and then to see if that value can actually make it back into the AST (maybe by having `cljs.js` code set `cljs.analyzer/*cljs-file*`). 

I know that David Nolen needed to abstract `cljs.js` away from I/O (or at least delegating the I/O to the client code), but perhaps he may be interested in a patch that optionally incorporates `:file` into the AST when it is actually available and meaningful to the bootstrapped environment. (Who knows, perhaps the meaning of `:file` in the AST needs to be broadened in scope to be a URL that could be either a `file://` or an `http://` as is done in https://github.com/clojure/clojurescript/wiki/Custom-REPLs#source-mapping ?)

**Comment by arichiardi** [comment]
I like the idea of passing back `:file` but as you said, I would probably call it `:file-path` or `:uri`.
We can ask tomorrow on Slack what he thinks of it.

In any case we could do the same in replumb, we have the source path and if the AST contains the namespace we can retrieve the file. It should work, I added the logic in the last two PR, following planck's.

For ASTs created in the repl session we won't probably have anything unless we store a "fake" file that includes all the evaluated expressions so far (prompt excluded of course)...I don't think it's worth it :)

**Comment by arichiardi** [comment]
Closed by #68

**Comment by arichiardi** [comment]
By the way this has become a patch!
http://dev.clojure.org/jira/browse/CLJS-1515

Thanks to @mfikes of course
