### ISSUE TITLE
Node.js: set! *target* causes issues

### ISSUE THREAD

**Issue by mfikes** [ScalaConsultants/replumb#20]
There is [a line](https://github.com/ScalaConsultants/replumb/blob/master/src/cljs/replumb/repl.cljs#L420) that reads:

```clojure
(set! *target* "default")
```

When compiling for Node.js, you typically set this to be `"nodejs"` (via a `:target :nodejs` [compiler option](https://github.com/clojure/clojurescript/wiki/Compiler-Options#target)).

Regardless, if you have this line in place, and are attempting `:optimizations :simple`, you get an error from Google Closure:

```
Nov 10, 2015 1:06:16 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /Users/mfikes/Projects/elbow/target/cljsbuild-compiler-0/replumb/repl.js:849: ERROR - @define variable cljs.core._STAR_target_STAR_ assignment must be global
cljs.core._STAR_target_STAR_ = "default";
^

Nov 10, 2015 1:06:16 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)
ERROR: JSC_NON_GLOBAL_DEFINE_INIT_ERROR. @define variable cljs.core._STAR_target_STAR_ assignment must be global at /Users/mfikes/Projects/elbow/target/cljsbuild-compiler-0/replumb/repl.js line 849 : 0
```

**Comment by arichiardi** [comment]
I have the problem here, just put here a [reference](https://developers.google.com/closure/compiler/docs/js-for-compiler?hl=en#tag-define).

**Comment by arichiardi** [comment]
Maybe I am asserting the  obvious, but probably we don't need to set \*target\* at all as it is already passed in at runtime and it is a compile only option.

**Comment by mfikes** [comment]
Yeah, I was thinking the same.
