### ISSUE TITLE
File key in load fn can be removed

### ISSUE THREAD

**Issue by mfikes** [ScalaConsultants/replumb#23]
In `replumb.load`, the load functions have an extra `file` key. The load fn defined by `cljs.js` actually does not work with a `file` key. This is a (perhaps misguided, or confusing) artifact of the way Planck works. (I had a desire to "overload" the load function, making it able to also load a file directly.) So, in short, this extra key can be removed.

**Comment by arichiardi** [comment]
Thanks, I think anyways `load` needs some rework, probably it will be split in `load.nodejs`, `load.js` and will contain specific platform `load-fn`.
