### ISSUE TITLE
Comments as input

### ISSUE THREAD

**Issue by tomasz-biernacki** [ScalaConsultants/replumb#25]
An input containing only a comment produces the following output:
```
cljs.user=> ;; this is a comment
EOF
```
If I write a comment after an expression it works fine: 
```
cljs.user=> (+ 1 2 3) ; another one
6
```

**Comment by arichiardi** [comment]
Ok I'll have a look at it, it works fine in the standard repl...probably there is warning thrown...

**Comment by arichiardi** [comment]
The issue might be upstream with `cljs.tools.reader/read-string`. Because `cljs.reader` correctly works.

I opened a JIRA issue: http://dev.clojure.org/jira/browse/TRDR-32

**Comment by arichiardi** [comment]
Given the helpful answer by @Bronsa here, I will need to wrap repl/read-string with a try catch.

**Comment by arichiardi** [comment]
Changed my mind a bit, keeping up with the "Design" section, I will leave it like this, where comments only do not constitute a valid reader object and therefore replumb throws an exception...
