### ISSUE TITLE
Thanks! Migrated my browser repl to replumb

### ISSUE THREAD

**Issue by joakin** [ScalaConsultants/replumb#33]
Hi!

Just wanted to share that I've migrated my browser repl project that I've used in workshops to teach ClojureScript to use replumb instead of a cheap copy&pasta from plank.

https://github.com/joakin/cljs-browser-repl/commit/8a65134b0662d80dbe4eee884d39a36b91275905

It was pretty straight forward, and I loved deleting the compiler code!

* https://github.com/joakin/cljs-browser-repl
* http://chimeces.com/cljs-browser-repl/

So, **thanks a lot** for making replumb, and thanks to @mfikes for tweeting about it!

I can submit a PR linking to the live demo in the README if you want.

Have a nice day! :sunny:

**Comment by arichiardi** [comment]
Oh now is a nice day :smile:

Thank you for using it and please do open a PR with links, it's going to be accepted for sure :wink:
