### ISSUE TITLE
Malfunctioning (require ..)

### ISSUE THREAD

**Issue by cfelde** [ScalaConsultants/replumb#40]
Hi,

This is very useful library, and I'm working on incorporating it into my own project as we speak. While playing with the repl browser demo I've noticed some odd behaviour. For example:

cljs.user=> (clojure.string/split "Test 1 2 3" #" ")
Use of undeclared Var clojure.string/split at line 1 
cljs.user=> (require 'clojure.string)
No such namespace: clojure.string, could not locate clojure/string.cljs, clojure/string.cljc, or Closure namespace "clojure.string"
cljs.user=> (clojure.string/split "Test 1 2 3" #" ")
["Test" "1" "2" "3"]

So at first the split function isn't available, so I do a (require ..). This shows an error, but still the split function is now actually available. Not sure if this is a bug or some other setup issue?

**Comment by cfelde** [comment]
Just noticed a new 0.1.2 release, so retested with that. Now get a different error on (require ..):

cljs.user=> (clojure.string/split "Test 1 2 3" #" ")
Use of undeclared Var clojure.string/split at line 1 
cljs.user=> (require 'clojure.string)
Could not require clojure.string - No *load-fn* set
cljs.user=> (clojure.string/split "Test 1 2 3" #" ")
["Test" "1" "2" "3"]

**Comment by arichiardi** [comment]
Yes, there was a bug in the `require` function that I fixed but not released yet, I am planning to have a quick release after having checked #39 at the beginning of the next week.

In the meantime (still to be documented, sorry) you can plug your own `:load-fn!` as option to `read-eval-call` as [you can see here](https://github.com/ScalaConsultants/replumb/blob/master/src/cljs/replumb/target.cljs#L28). Like so:

```
(require [replumb.target :as target])
(replumb/read-eval-call {:load-fn! target/fake-load-fn!} (partial handle-result! console) line)
```

This will trick `cljs.js` to load even if source cannot be found and then `clojure.string` will work.

In general, the require functionality is the most difficult to implement as there is IO involved that client code needs to provide. It is the area I am working the most at, by now. Therefore you can still find quirks.

Thanks for testing and reporting!

**Comment by cfelde** [comment]
Thanks for the tip about the fake-load-fn!, I can use that to avoid having the error printed if I create a dummy function that does nothing.

**Comment by arichiardi** [comment]
It will be improved don't worry :smile

**Comment by cfelde** [comment]
Does the job ;) Replumb has been very helpful for my little Excel/ClojureScript REPL project, so keep it up!

**Comment by arichiardi** [comment]
Thanks for the kind words, I have been trying to have a neader API, so far in another branch, still not finished though ;)
