### ISSUE TITLE
Eval cache

### ISSUE THREAD

**Issue by arichiardi** [ScalaConsultants/replumb#42]
Add eval cache loading at runtime, for nodejs, but for browsers with *load-fn* support too.

Investigate:
https://gist.github.com/mhuebert/18a1ef480d1bb0b0a270

https://github.com/mfikes/planck/blob/master/planck-cljs/src/planck/repl.cljs#L376

**Comment by mfikes** [comment]
I recently wrote (at a high level) about Planck's cache feature: http://blog.fikesfarm.com/posts/2015-11-26-planck-caching.html

**Comment by arichiardi** [comment]
>  All you need to do is arrange to have the cached info persisted to disk.

This is exactly what I am trying to make simpler in the `require-rework` branch. I still consider providing `io` directly in `replumb` not an easy task. For example in node you might want to specify the `encoding` of your files, or for a browser a remote location.

The current `read-file-fn` can be exposed as api but it feels constrictive. Maybe `read-resource-fn` is a better name for that and replumb will take care of caching. Where though? (I am thinking aloud).
Again, a function `write-cache-fn` could be plugged by client code that writes wherever needed.

Does all this make sense?
:smile:

**Comment by arichiardi** [comment]
Thanks to @mfikes as usual, we already have test cases :smile: 

```
;; without loading core.cljs.cache.aot.json a bunch of warnings
;; should appear for each and every symbol in cljs.core
baz.quux=> (map inc [1 2 3])
WARNING: Use of undeclared Var baz.quux/map at line 1 
WARNING: Use of undeclared Var cljs.core/inc at line 1 
undefined is not an object (evaluating 'baz.quux.map.call')

baz.quux=> (cljs.core/map inc [1 2 3])
WARNING: Use of undeclared Var cljs.core/map at line 1 
WARNING: Use of undeclared Var cljs.core/inc at line 1 
(2 3 4)
```

Same reasoning for other namespaces (see last evaluation):

```
foo.bar=> (ns baz.quux)
nil
baz.quux=> (foo.bar/square 3)
9
baz.quux=> (do (planck.repl/purge-analysis-cache! planck.repl/st 'foo.bar) nil)
WARNING: No such namespace: planck.repl, could not locate planck/repl.cljs, planck/repl.cljc, or Closure namespace "" at line 1 
WARNING: Use of undeclared Var planck.repl/purge-analysis-cache! at line 1 
WARNING: No such namespace: planck.repl, could not locate planck/repl.cljs, planck/repl.cljc, or Closure namespace "" at line 1 
WARNING: Use of undeclared Var planck.repl/st at line 1 
nil
baz.quux=> (foo.bar/square 3)
WARNING: No such namespace: foo.bar, could not locate foo/bar.cljs, foo/bar.cljc, or Closure namespace "" at line 1 
WARNING: Use of undeclared Var foo.bar/square at line 1 
9
```
