### ISSUE TITLE
Performance of defn in Safari

### ISSUE THREAD

**Issue by arichiardi** [ScalaConsultants/replumb#45]
There might be some slowness due to [CLJS-1381](http://dev.clojure.org/jira/browse/CLJS-1381).

We might need to add ```:static-fns true``` to `cljsbuild` and [this](https://github.com/mfikes/planck/blob/master/planck-cljs/src/planck/repl.cljs#L742).

This can also solve poor performance of `(list 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18)`.

Thanks @mfikes for the heads-up :+1:

**Comment by mfikes** [comment]
For the list expression, you need to specify `:static-fns` when using `cljs.js`. (This is the change in the compiler behind http://blog.fikesfarm.com/posts/2015-11-03-planck-static-function-dispatch.html)
