### ISSUE TITLE
Does not correctly require ns without a refer

### ISSUE THREAD

**Issue by arichiardi** [ScalaConsultants/replumb#49]
Still seems something is wrong with `require`. I have to admit I need to add more tests.
One can be the following (should succeed):

```
# lein node-repl*
# node dev-resources/private/node/compiled/nodejs-repl.js src/node
cljs.user=> (force replumb.nodejs.io/require-fs)
Use of undeclared Var replumb.nodejs.io/require-fs at line 1 
```

The following works but it is weird:
```
cljs.user=> (require 'replumb.nodejs.io)
nil
cljs.user=> (replumb.nodejs.io/read-file! "dev-resources/public/index.html" (fn [src] (println src)))
Use of undeclared Var replumb.nodejs.io/read-file! at line 1 ;; <-- This?
cljs.user=> <!DOCTYPE html>
<html>
  <body>
    <link href="styles/console.css" rel="stylesheet" type="text/css">

    <div id="app"></div>
    <script src="js/compiled/replumb-repl.js"></script>
    <script>replumb_repl.core.main();</script>
  </body>
</html>
```

And the following works:
```
# lein node-repl*
# node dev-resources/private/node/compiled/nodejs-repl.js src/node
(require '[replumb.nodejs.io :refer [read-file! require-fs]])
cljs.user=> (force require-fs)
#js {:Stats #object[Function "function (
    dev,
    mode,
    nlink,
    uid,
...
cljs.user=> (read-file! "dev-resources/public/index.html" (fn [src] (println src)))
nil
cljs.user=> <!DOCTYPE html>
<html>
  <body>
    <link href="styles/console.css" rel="stylesheet" type="text/css">

    <div id="app"></div>
    <script src="js/compiled/replumb-repl.js"></script>
    <script>replumb_repl.core.main();</script>
  </body>
</html>
```

I am a bit tired so it might be trivial...

**Comment by mfikes** [comment]
That is indeed odd. Plank has never exhibited that behavior.

**Comment by arichiardi** [comment]
For `clojurescript/core` @mfikes and @swannodette maybe you already know this but:

```
cljs.user=> (require 'foo.bar.baz)
Initializing REPL environment with data {:form (require 'foo.bar.baz), :ns cljs.user, :target :nodejs}

Evaluating  (require (quote foo.bar.baz))  with options  {:target :nodejs, :src-paths [dev-resources/private/test/src/cljs], :verbose true}
Processing :require via (ns cljs.user (:require [foo.bar.baz]))
...
cljs.user=> a
"whatever"
```

under the hood generates a warning (`:warning-type :undeclared-var`) but `cljs.js/eval-str` returns a `{:value ...}` map. I could observe this because `replumb` can be set to `{:warning-as-error true}`.

I know it is minor. Any thought?

**Comment by mfikes** [comment]
@arichiardi The analyzer emits the warning, but then generates the code because it is just a warning. Then the code is executed and you get back a `{:value ...}` map just as if you had executed `(js* "cljs.user.a")` and got back `nil`.

I'm unfamiliar with turning warnings into errors.

**Comment by arichiardi** [comment]
Great thanks for the answer...yes the second part is an optional feature I added (here)[https://github.com/ScalaConsultants/replumb/blob/master/src/cljs/replumb/repl.cljs#L255).

It is useful for repl especially for undeclared var. I am planning to extend the functionality from a simple on-off.

The above problem can be an "issue" for user though as they will get an error whereas the code path completes successfully. Maybe I will need to suppress directly the warning from the analyzer.
