### ISSUE TITLE
Use cljs.js/require instead of duplicating its functionalities

### ISSUE THREAD

**Issue by arichiardi** [ScalaConsultants/replumb#52]
In particular I am wondering if the `process-reloads!` [here](https://github.com/ScalaConsultants/replumb/blob/master/src/cljs/replumb/repl.cljs#L174) is needed.

By checking [cljs.js/require](https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/js.cljs#L221) source, it looks like we won't need to purge any namespace but I might of course be wrong and need again some help from @mfikes / planck :smile:

After that, and now that require is kind of working, I need to deeply test this functionality.

**Comment by arichiardi** [comment]
I might even try to use require (it is a fn after all...) directly and see what happens ;)

**Comment by arichiardi** [comment]
After conversation with @mfikes I would just like to report that it is not possible to use `cljs.js/require` as it does not cover all the corner cases of the current way to require a namespace through `ns`: `(ns current-ns :require [....]).

So this PR will stay open only for reminding me/contributors to implement some tests around `:reload`.

**Comment by mfikes** [comment]
Original ref http://clojurians-log.mantike.pro/cljs-dev/2015-08-11.html

```
mfikes 03:33:48
@dnolen: I'm thinking about supporting :as in Plank's require REPL special by simply invoking the ns special. (cljs.js/require doesn’t support :as right?)
dnolen 03:35:00
@mfikes: yeah it doesn’t, cljs.js/require is only about library loading doesn’t support any ns features (all that happens through the ns form)
mfikes 03:35:34
@dnolen: Thx. I’ll imitate what cljs.repl does by using ns and then bouncing back to the orginial ns
dnolen 03:36:54
@mfikes: that’s really the simplest way - trying to make the ns stuff work at runtime would mean getting very serious about reifying namespaces
dnolen 03:37:11
that’s a lot of work for little payoff, since ns form gives you an approximate simulation.
mfikes 03:37:23
yeah
```

**Comment by arichiardi** [comment]
Thanks! It is good to have a good place to store these already answered questions.
