### ISSUE TITLE
Missing doc for ns-interns

### ISSUE THREAD

**Issue by arichiardi** [ScalaConsultants/replumb#81]
In `lein node-repl` we can observe:
```
cljs.user=> (doc ns-interns)
-------------------------
cljs.core/ns-interns
  nil
```

while it should be:
```
-------------------------
cljs.core/ns-interns
(quote ([[quote ns]]))
Macro
  Returns a map of the intern mappings for the namespace.
nil
```

**Comment by tomasz-biernacki** [comment]
Since this is a macro this should be related to #85 (both `source` and `doc` rely on `get-var`)

**Comment by arichiardi** [comment]
So maybe I should unveil [this trick](https://github.com/ScalaConsultants/replumb/blob/master/src/cljs/replumb/doc_maps.cljs#L156).

**Comment by arichiardi** [comment]
They are two different problems, I am solving this one, related with [CLJS-1335](http://dev.clojure.org/jira/browse/CLJS-1335).
