### ISSUE TITLE
When implicit macro loading :refer-macros fails

### ISSUE THREAD

**Issue by tomasz-biernacki** [ScalaConsultants/replumb#91]
For context see "Inline macro specification" section [here](https://github.com/clojure/clojurescript/wiki/Differences-from-Clojure#namespaces).

Here the error:
```
cljs.user=> (ns my.namespace (:require [foo.bar.baz :refer-macros [mul-baz]]))
Could not parse ns form my.namespace - Referred macro foo.bar.baz/mul-baz does not exist
```

see also [jira issue](http://dev.clojure.org/jira/browse/CLJS-1507) (probably related)

**Comment by tomasz-biernacki** [comment]
Seems to be working in `1.7.202`.
Failing tests have been added for now (`1.7.170`); when the bug will be solved these tests will be replaced with passing ones.

**Comment by arichiardi** [comment]
:+1:

**Comment by arichiardi** [comment]
I would add a small description of the context of implicit macro loading (I can do it to in your first post if you want) and maybe show a sample namespace `foo.test` that requires implicitly a macro.
